name: digi_14
description: Flutter app for fetching data from api

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  equatable: ^2.0.3
  flutter_bloc: ^7.3.0
  flutter_screenutil: ^5.5.3+2
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  flutter_svg:
  sentry_flutter: ^5.1.0
  separated_column:
  flutter_swipe_detector:


dev_dependencies:
  bloc_test: ^8.2.0
  mocktail: ^0.2.0
  test: ^1.20.1
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Avenir-Book
      fonts:

        - asset: fonts/Avenir-Book.ttf
    - family: Avenir-Roman
      fonts:
        - asset: fonts/Avenir-Roman.ttf
    - family: Avenir-Heavy
      fonts:
        - asset: fonts/Avenir-Heavy.ttf
    - family: Avenir-Medium
      fonts:
        - asset: fonts/Avenir-Medium.ttf
    - family: Avenir-Medium-Oblique
      fonts:
        - asset: fonts/Avenir-Medium-Oblique.ttf
    - family: Avenir_Regular
      fonts:
        - asset: fonts/Avenir_Regular.ttf
    - family: Avenir-Extra-Bold
      fonts:
        - asset: fonts/Avenir-ExtraBoldItalic.ttf
    - family: Avenir-Light
      fonts:
        - asset: fonts/Avenir_Light.ttf
    - family: Avenir-Bold
      fonts:
        - asset: fonts/Avenir_Light.ttf
    - family: Inter-Medium
      fonts:
        - asset: fonts/Inter_Medium_500.ttf

















